target("RHITest2_Triangle")
    add_luna_sdk_options()
    add_rules("luna.shader")
    set_group("Tests/RHITest")
    set_kind("binary")
    add_files("TestTriangleVS.hlsl", {type = "vertex"})
    add_files("TestTrianglePS.hlsl", {type = "pixel"})
    add_files("*.cpp")
    add_deps("Runtime", "RHI", "RHITestBed", "ShaderCompiler")
    -- before_build(function(target)
    --     import("compile_shader")
    --     compile_shader.shader_to_cpp("TestTriangleVS.hlsl", "vertex")
    --     compile_shader.shader_to_cpp("TestTrianglePS.hlsl", "pixel")
    -- end)
target_end()