target("RHITest2_Triangle")
    add_luna_sdk_options()
    add_rules("luna.shader")
    set_group("Tests/RHITest")
    set_kind("binary")
    add_luna_shader("TestTriangleVS.cxx", {type = "vertex", entry_point = "vs_main"})
    add_luna_shader("TestTrianglePS.cxx", {type = "pixel", entry_point = "ps_main"})
    add_files("*.cpp")
    add_deps("Runtime", "RHI", "RHITestBed")
target_end()
