target("ImageCSharpTest")
    set_kind("binary")
    set_group("Tests")
    add_files("Main.cs")
    add_deps("Luna.Runtime", "Luna.Image")
    set_luna_sdk_csharp_options()
    after_build(function(target)
        local target_dir = target:targetdir()
        os.cp(path.join("$(projectdir)", "Tests", "RHITests", "RHITest3_Texture", "uv_checker.png"), path.join(target_dir, "uv_checker.png"))
    end)
    after_clean(function(target)
        os.rm(path.join(target:targetdir(), "uv_checker.png"))
    end)
target_end()
