using System.Text;
using CPPSL.Core.Compiler;
using CPPSL.Core.IR;
using CPPSL.Core.Semantics;

namespace CPPSL.Core.Output;

internal abstract class CppslShaderSourceEmitterBase
{
    protected static void WriteHeader(StringBuilder builder, string targetName, CppslCompileOptions options)
    {
        builder.AppendLine("// Generated by cppslc phase 0.");
        builder.AppendLine($"// Target: {targetName}");
        builder.AppendLine($"// Entry: {options.EntryPoint}");
        builder.AppendLine($"// Stage: {options.Stage}");
        builder.AppendLine("// Function body was lowered from CPPSL IR phase 0.");
        builder.AppendLine();
    }

    protected static CppslFunction? FindEntryPoint(CppslCompileOptions options, CppslSemanticModel model)
    {
        return model.Functions.FirstOrDefault(function => function.Name == options.EntryPoint);
    }

    protected static string UnwrapTemplateArgument(string type)
    {
        var open = type.IndexOf('<');
        var close = type.LastIndexOf('>');
        if (open < 0 || close <= open)
        {
            return type;
        }

        return type.Substring(open + 1, close - open - 1).Trim();
    }

    protected void WriteFunctionBody(
        StringBuilder builder,
        CppslFunction entryPoint,
        CppslSemanticModel model,
        CppslIrModule irModule)
    {
        var irEntryPoint = irModule.EntryPoints.FirstOrDefault(entry => entry.Name == entryPoint.Name);
        builder.AppendLine("{");
        if (irEntryPoint?.Body is null)
        {
            WriteDefaultReturn(builder, entryPoint.ReturnType ?? "void", model, 1);
        }
        else
        {
            WriteStatementChildren(builder, irEntryPoint.Body, 1);
        }
        builder.AppendLine("}");
    }

    protected void WriteStatementChildren(StringBuilder builder, CppslIrNode node, int indent)
    {
        foreach (var child in node.Children)
        {
            WriteStatement(builder, child, indent);
        }
    }

    protected void WriteStatement(StringBuilder builder, CppslIrNode node, int indent)
    {
        var prefix = new string(' ', indent * 4);
        switch (node.Kind)
        {
            case "DeclarationStatement":
                foreach (var child in node.Children.Where(static child => child.Kind == "LocalVariable"))
                {
                    builder.AppendLine($"{prefix}{MapValueType(child.Type ?? string.Empty)} {child.Spelling};");
                }
                break;
            case "OperatorCallExpression" when node.DisplayName == "operator=" && node.Children.Count >= 3:
                builder.AppendLine($"{prefix}{LowerExpression(node.Children[1])} = {LowerExpression(node.Children[2])};");
                break;
            case "ReturnStatement" when node.Children.Count != 0:
                builder.AppendLine($"{prefix}return {LowerExpression(node.Children[^1])};");
                break;
            default:
                if (IsExpressionNode(node))
                {
                    builder.AppendLine($"{prefix}{LowerExpression(node)};");
                }
                break;
        }
    }

    protected string LowerExpression(CppslIrNode node)
    {
        return node.Kind switch
        {
            "ImplicitCastExpression" or "ParenExpression" or "ConstructorCallExpression" when node.Children.Count == 1 =>
                LowerExpression(node.Children[0]),
            "DeclRefExpression" => node.DisplayName ?? node.Spelling,
            "MemberExpression" when node.Children.Count == 1 =>
                $"{LowerExpression(node.Children[0])}.{node.DisplayName}",
            "OperatorCallExpression" when node.DisplayName == "operator->" && node.Children.Count >= 2 =>
                LowerExpression(node.Children[^1]),
            "OperatorCallExpression" when node.DisplayName is "operator=" && node.Children.Count >= 3 =>
                $"{LowerExpression(node.Children[1])} = {LowerExpression(node.Children[2])}",
            "CallExpression" => LowerCallExpression(node),
            "FunctionalCastExpression" => LowerFunctionalCast(node),
            "InitializerListExpression" => string.Join(", ", node.Children.Select(LowerExpression)),
            "FloatingLiteral" => FormatFloatingLiteral(node.Spelling),
            "IntegerLiteral" or "BooleanLiteral" or "StringLiteral" => node.Spelling,
            _ when node.Children.Count == 1 => LowerExpression(node.Children[0]),
            _ => node.Spelling
        };
    }

    protected virtual string LowerCallExpression(CppslIrNode node)
    {
        var name = node.DisplayName ?? node.Spelling;
        var arguments = node.Children
            .Skip(IsCalleeReference(node.Children.FirstOrDefault(), name) ? 1 : 0)
            .Select(LowerExpression)
            .ToArray();

        if (name == "mul" && arguments.Length == 2)
        {
            return LowerMul(arguments[0], arguments[1]);
        }

        return $"{name}({string.Join(", ", arguments)})";
    }

    protected virtual string LowerFunctionalCast(CppslIrNode node)
    {
        var type = MapValueType(node.Type ?? node.TypeInfo?.Spelling ?? node.Spelling);
        var argumentList = node.Children.Count == 1 && node.Children[0].Kind == "InitializerListExpression"
            ? LowerExpression(node.Children[0])
            : string.Join(", ", node.Children.Select(LowerExpression));
        return $"{type}({argumentList})";
    }

    protected virtual string LowerMul(string left, string right)
    {
        return $"({left} * {right})";
    }

    protected virtual string FormatFloatingLiteral(string spelling)
    {
        return spelling;
    }

    protected void WriteDefaultReturn(StringBuilder builder, string returnType, CppslSemanticModel model, int indent)
    {
        if (returnType == "void")
        {
            return;
        }

        var prefix = new string(' ', indent * 4);
        builder.Append(prefix);
        builder.Append("return ");
        builder.Append(DefaultValue(returnType, model));
        builder.AppendLine(";");
    }

    protected string DefaultValue(string type, CppslSemanticModel model)
    {
        if (model.Structs.FirstOrDefault(structure => structure.Name == type) is { } structure)
        {
            return DefaultStructValue(structure, model);
        }

        var mappedType = MapValueType(type);
        return mappedType switch
        {
            "bool" => "false",
            "int" => "0",
            "uint" => "0u",
            "float" => "0.0",
            _ => DefaultAggregateValue(mappedType)
        };
    }

    protected abstract string MapValueType(string type);

    protected abstract string DefaultStructValue(CppslStruct structure, CppslSemanticModel model);

    protected abstract string DefaultAggregateValue(string mappedType);

    private static bool IsCalleeReference(CppslIrNode? node, string calleeName)
    {
        if (node is null)
        {
            return false;
        }

        if (node.Kind == "DeclRefExpression" && node.DisplayName == calleeName)
        {
            return true;
        }

        return node.Children.Count == 1 && IsCalleeReference(node.Children[0], calleeName);
    }

    private static bool IsExpressionNode(CppslIrNode node)
    {
        return node.Kind.EndsWith("Expression", StringComparison.Ordinal) ||
            node.Kind.EndsWith("Literal", StringComparison.Ordinal) ||
            node.Kind == "DeclRefExpression" ||
            node.Kind == "MemberExpression" ||
            node.Kind == "OperatorCallExpression" ||
            node.Kind == "CallExpression";
    }
}
