using System.Text;
using System.Text.RegularExpressions;
using CPPSL.Core.Compiler;
using CPPSL.Core.IR;
using CPPSL.Core.Semantics;

namespace CPPSL.Core.Output;

internal abstract class CppslShaderSourceEmitterBase
{
    protected static void WriteHeader(StringBuilder builder, string targetName, CppslCompileOptions options)
    {
        builder.AppendLine("// Generated by cppslc phase 0.");
        builder.AppendLine($"// Target: {targetName}");
        builder.AppendLine($"// Entry: {options.EntryPoint}");
        builder.AppendLine($"// Stage: {options.Stage}");
        builder.AppendLine("// Function body was lowered from CPPSL IR phase 0.");
        builder.AppendLine();
    }

    protected static CppslFunction? FindEntryPoint(CppslCompileOptions options, CppslSemanticModel model)
    {
        return model.Functions.FirstOrDefault(function => function.Name == options.EntryPoint);
    }

    protected static string UnwrapTemplateArgument(string type)
    {
        var open = type.IndexOf('<');
        var close = type.LastIndexOf('>');
        if (open < 0 || close <= open)
        {
            return type;
        }

        return type.Substring(open + 1, close - open - 1).Trim();
    }

    protected static string ResourceElementType(CppslGlobal global)
    {
        return global.ResourceKind switch
        {
            "constant_buffer" or "structured_buffer" or "rw_structured_buffer"
                when global.Type.Contains('<', StringComparison.Ordinal) => UnwrapTemplateArgument(global.Type),
            "structured_buffer" or "rw_structured_buffer" => TrimTopLevelConst(TrimPointerOrArrayType(global.Type)),
            _ => global.Type
        };
    }

    protected static bool TryGetTextureValueType(CppslIrNode node, out string valueType)
    {
        foreach (var candidate in EnumerateNodeTypeCandidates(node))
        {
            if (TryExtractTextureValueType(candidate, out valueType))
            {
                return true;
            }
        }

        foreach (var child in node.Children)
        {
            if (TryGetTextureValueType(child, out valueType))
            {
                return true;
            }
        }

        valueType = string.Empty;
        return false;
    }

    protected static string NormalizeShaderTypeName(string type)
    {
        return type
            .Replace("const ", string.Empty, StringComparison.Ordinal)
            .Replace("struct ", string.Empty, StringComparison.Ordinal)
            .Replace("class ", string.Empty, StringComparison.Ordinal)
            .Replace("cppsl::", string.Empty, StringComparison.Ordinal)
            .Trim();
    }

    protected static IReadOnlySet<string> DescriptorSetLayoutStructNames(CppslSemanticModel model)
    {
        return model.Globals
            .Where(static global => global.IsDescriptorSet)
            .Select(static global => global.Type)
            .ToHashSet(StringComparer.Ordinal);
    }

    protected static bool TryGetAccessPath(CppslIrNode node, out string accessPath)
    {
        if (node.Kind == "DeclRefExpression")
        {
            accessPath = node.DisplayName ?? node.Spelling;
            return accessPath.Length != 0;
        }

        if (node.Kind == "MemberExpression" &&
            node.DisplayName is not null &&
            node.Children.Count == 1 &&
            TryGetAccessPath(node.Children[0], out var receiver))
        {
            accessPath = $"{receiver}.{node.DisplayName}";
            return true;
        }

        accessPath = string.Empty;
        return false;
    }

    protected static string RewriteResidualResourceAccessPaths(
        string source,
        CppslSemanticModel model,
        Func<CppslGlobal, string> replacementFactory)
    {
        foreach (var global in model.Globals.Where(static global => global.ResourceKind is not null && global.AccessPath is not null))
        {
            var pattern = $@"(?<![A-Za-z0-9_\.]){Regex.Escape(global.AccessPath!)}(?![A-Za-z0-9_])";
            source = Regex.Replace(source, pattern, replacementFactory(global));
        }

        return source;
    }

    protected static string FormatVariableDeclaration(string mappedType, string name)
    {
        var bracketIndex = mappedType.IndexOf('[');
        if (bracketIndex < 0)
        {
            return $"{mappedType} {name}";
        }

        var baseType = mappedType[..bracketIndex].TrimEnd();
        var suffix = mappedType[bracketIndex..];
        return $"{baseType} {name}{suffix}";
    }

    private static string TrimPointerOrArrayType(string type)
    {
        var trimmed = type.Trim();
        while (trimmed.EndsWith('*'))
        {
            trimmed = trimmed[..^1].TrimEnd();
        }

        var arrayIndex = trimmed.IndexOf('[');
        return arrayIndex < 0 ? trimmed : trimmed[..arrayIndex].TrimEnd();
    }

    private static string TrimTopLevelConst(string type)
    {
        var trimmed = type.Trim();
        return trimmed.StartsWith("const ", StringComparison.Ordinal)
            ? trimmed["const ".Length..].TrimStart()
            : trimmed;
    }

    private static IEnumerable<string> EnumerateNodeTypeCandidates(CppslIrNode node)
    {
        if (!string.IsNullOrWhiteSpace(node.Type))
        {
            yield return node.Type!;
        }
        if (!string.IsNullOrWhiteSpace(node.TypeInfo?.Spelling))
        {
            yield return node.TypeInfo!.Spelling;
        }
        if (!string.IsNullOrWhiteSpace(node.TypeInfo?.CanonicalName))
        {
            yield return node.TypeInfo!.CanonicalName;
        }
        if (!string.IsNullOrWhiteSpace(node.TypeInfo?.DesugaredName))
        {
            yield return node.TypeInfo!.DesugaredName;
        }
    }

    private static bool TryExtractTextureValueType(string typeName, out string valueType)
    {
        var normalized = NormalizeShaderTypeName(typeName);
        if (normalized.Contains("Texture1D<", StringComparison.Ordinal) ||
            normalized.Contains("Texture2D<", StringComparison.Ordinal) ||
            normalized.Contains("DepthTexture2D<", StringComparison.Ordinal) ||
            normalized.Contains("Texture3D<", StringComparison.Ordinal) ||
            normalized.Contains("RWTexture1D<", StringComparison.Ordinal) ||
            normalized.Contains("RWTexture2D<", StringComparison.Ordinal) ||
            normalized.Contains("RWTexture3D<", StringComparison.Ordinal))
        {
            valueType = NormalizeShaderTypeName(UnwrapTemplateArgument(normalized));
            return true;
        }

        valueType = string.Empty;
        return false;
    }

    protected void WriteFunctionBody(
        StringBuilder builder,
        CppslFunction entryPoint,
        CppslSemanticModel model,
        CppslIrModule irModule)
    {
        var irEntryPoint = irModule.EntryPoints.FirstOrDefault(entry => entry.Name == entryPoint.Name);
        builder.AppendLine("{");
        if (irEntryPoint?.Body is null)
        {
            WriteDefaultReturn(builder, entryPoint.ReturnType ?? "void", model, 1);
        }
        else
        {
            WriteStatementChildren(builder, irEntryPoint.Body, 1);
        }
        builder.AppendLine("}");
    }

    protected void WriteFunctionBody(
        StringBuilder builder,
        CppslFunction function,
        CppslSemanticModel model,
        CppslIrNode? body)
    {
        builder.AppendLine("{");
        if (body is null)
        {
            WriteDefaultReturn(builder, function.ReturnType ?? "void", model, 1);
        }
        else
        {
            WriteStatementChildren(builder, body, 1);
        }
        builder.AppendLine("}");
    }

    protected void WriteStatementChildren(StringBuilder builder, CppslIrNode node, int indent)
    {
        foreach (var child in node.Children)
        {
            WriteStatement(builder, child, indent);
        }
    }

    protected void WriteStatement(StringBuilder builder, CppslIrNode node, int indent)
    {
        var prefix = new string(' ', indent * 4);
        switch (node.Kind)
        {
            case "CompoundStatement":
                builder.AppendLine($"{prefix}{{");
                WriteStatementChildren(builder, node, indent + 1);
                builder.AppendLine($"{prefix}}}");
                break;
            case "DeclarationStatement":
                foreach (var child in node.Children.Where(static child => child.Kind == "LocalVariable"))
                {
                    var initializerNode = child.Children.LastOrDefault();
                    var hasExplicitInitializer = initializerNode is not null &&
                        !(initializerNode.Kind == "ConstructorCallExpression" && initializerNode.Children.Count == 0);
                    var initializer = !hasExplicitInitializer
                        ? string.Empty
                        : $" = {LowerExpression(initializerNode!)}";
                    builder.AppendLine($"{prefix}{MapValueType(child.Type ?? string.Empty)} {child.Spelling}{initializer};");
                }
                break;
            case "OperatorCallExpression" when TryMapAssignmentOperator(node.DisplayName, out var op) && node.Children.Count >= 3:
                builder.AppendLine($"{prefix}{LowerExpression(node.Children[1])} {op} {LowerExpression(node.Children[2])};");
                break;
            case "BinaryOperator" when IsAssignmentOperator(node.DisplayName) && node.Children.Count >= 2:
                builder.AppendLine($"{prefix}{LowerExpression(node.Children[0])} {node.DisplayName} {LowerExpression(node.Children[1])};");
                break;
            case "ReturnStatement" when node.Children.Count != 0:
                builder.AppendLine($"{prefix}return {LowerExpression(node.Children[^1])};");
                break;
            case "ReturnStatement":
                builder.AppendLine($"{prefix}return;");
                break;
            case "IfStatement" when node.Children.Count >= 2:
                builder.AppendLine($"{prefix}if ({LowerExpression(node.Children[0])})");
                WriteEmbeddedStatement(builder, node.Children[1], indent);
                if (node.Children.Count >= 3)
                {
                    builder.AppendLine($"{prefix}else");
                    WriteEmbeddedStatement(builder, node.Children[2], indent);
                }
                break;
            case "WhileStatement" when node.Children.Count >= 2:
                builder.AppendLine($"{prefix}while ({LowerExpression(node.Children[0])})");
                WriteEmbeddedStatement(builder, node.Children[1], indent);
                break;
            case "ForStatement" when node.Children.Count >= 4:
                builder.AppendLine($"{prefix}for ({LowerForInitializer(node.Children[0])}; {LowerExpression(node.Children[1])}; {LowerExpression(node.Children[2])})");
                WriteEmbeddedStatement(builder, node.Children[3], indent);
                break;
            case "ContinueStatement":
                builder.AppendLine($"{prefix}continue;");
                break;
            case "BreakStatement":
                builder.AppendLine($"{prefix}break;");
                break;
            default:
                if (IsExpressionNode(node))
                {
                    builder.AppendLine($"{prefix}{LowerExpression(node)};");
                }
                break;
        }
    }

    private void WriteEmbeddedStatement(StringBuilder builder, CppslIrNode node, int indent)
    {
        if (node.Kind == "CompoundStatement")
        {
            WriteStatement(builder, node, indent);
            return;
        }

        var prefix = new string(' ', indent * 4);
        builder.AppendLine($"{prefix}{{");
        WriteStatement(builder, node, indent + 1);
        builder.AppendLine($"{prefix}}}");
    }

    protected virtual string LowerExpression(CppslIrNode node)
    {
        return node.Kind switch
        {
            "ImplicitCastExpression" or "ParenExpression" or "ConstructorCallExpression" when node.Children.Count == 1 =>
                LowerExpression(node.Children[0]),
            "CStyleCastExpression" when node.Children.Count == 1 =>
                $"({MapValueType(node.Type ?? node.TypeInfo?.Spelling ?? string.Empty)}){LowerExpression(node.Children[0])}",
            "DeclRefExpression" => node.DisplayName ?? node.Spelling,
            "MemberExpression" when node.Children.Count == 1 =>
                $"{LowerExpression(node.Children[0])}.{node.DisplayName}",
            "ArraySubscriptExpression" when node.Children.Count >= 2 =>
                $"{LowerExpression(node.Children[0])}[{LowerExpression(node.Children[1])}]",
            "OperatorCallExpression" when node.DisplayName == "operator->" && node.Children.Count >= 2 =>
                LowerExpression(node.Children[^1]),
            "BinaryOperator" when node.DisplayName is "=" && node.Children.Count >= 2 =>
                $"{LowerExpression(node.Children[0])} = {LowerExpression(node.Children[1])}",
            "BinaryOperator" when IsAssignmentOperator(node.DisplayName) && node.Children.Count >= 2 =>
                $"{LowerExpression(node.Children[0])} {node.DisplayName} {LowerExpression(node.Children[1])}",
            "BinaryOperator" when node.Children.Count >= 2 && IsBinaryOperator(node.DisplayName) =>
                $"({LowerExpression(node.Children[0])} {node.DisplayName} {LowerExpression(node.Children[1])})",
            "ConditionalOperator" when node.Children.Count >= 3 =>
                $"({LowerExpression(node.Children[0])} ? {LowerExpression(node.Children[1])} : {LowerExpression(node.Children[2])})",
            "OperatorCallExpression" when TryMapBinaryOperator(node.DisplayName, out var op) && node.Children.Count >= 3 =>
                $"({LowerExpression(node.Children[1])} {op} {LowerExpression(node.Children[2])})",
            "OperatorCallExpression" when node.DisplayName is "operator=" && node.Children.Count >= 3 =>
                $"{LowerExpression(node.Children[1])} = {LowerExpression(node.Children[2])}",
            "UnaryOperator" when node.Children.Count >= 1 && IsIncrementOperator(node.DisplayName) =>
                node.Spelling,
            "UnaryOperator" when node.Children.Count >= 1 && IsPrefixUnaryOperator(node.DisplayName) =>
                $"{node.DisplayName}{LowerExpression(node.Children[0])}",
            "CallExpression" => LowerCallExpression(node),
            "FunctionalCastExpression" => LowerFunctionalCast(node),
            "InitializerListExpression" => LowerInitializerList(node),
            "FloatingLiteral" => FormatFloatingLiteral(node.Spelling),
            "IntegerLiteral" or "BooleanLiteral" or "StringLiteral" => node.Spelling,
            _ when node.Children.Count == 1 => LowerExpression(node.Children[0]),
            _ => node.Spelling
        };
    }

    protected virtual string LowerCallExpression(CppslIrNode node)
    {
        if (TryGetMemberCall(node, out var receiver, out var memberName, out var memberArguments))
        {
            return LowerMemberCall(receiver, memberName, memberArguments);
        }

        var name = node.DisplayName ?? node.Spelling;
        var arguments = node.Children
            .Skip(IsCalleeReference(node.Children.FirstOrDefault(), name) ? 1 : 0)
            .Select(LowerExpression)
            .ToArray();

        if (name == "mul" && arguments.Length == 2)
        {
            return LowerMul(arguments[0], arguments[1]);
        }

        return $"{name}({string.Join(", ", arguments)})";
    }

    private static bool IsBinaryOperator(string? displayName)
    {
        return displayName is "+" or "-" or "*" or "/" or "%" or
            "==" or "!=" or "<" or ">" or "<=" or ">=" or
            "&&" or "||" or "&" or "|" or "^" or "<<" or ">>";
    }

    private static bool IsAssignmentOperator(string? displayName)
    {
        return displayName is "=" or "+=" or "-=" or "*=" or "/=" or "%=" or "&=" or "|=" or "^=" or "<<=" or ">>=";
    }

    private static bool IsPrefixUnaryOperator(string? displayName)
    {
        return displayName is "+" or "-" or "!" or "~";
    }

    private static bool IsIncrementOperator(string? displayName)
    {
        return displayName is "++" or "--";
    }

    private static bool TryMapBinaryOperator(string? displayName, out string op)
    {
        op = displayName switch
        {
            "operator+" => "+",
            "operator-" => "-",
            "operator*" => "*",
            "operator/" => "/",
            "operator%" => "%",
            "operator==" => "==",
            "operator!=" => "!=",
            "operator<" => "<",
            "operator>" => ">",
            "operator<=" => "<=",
            "operator>=" => ">=",
            "operator&&" => "&&",
            "operator||" => "||",
            "operator&" => "&",
            "operator|" => "|",
            "operator^" => "^",
            "operator<<" => "<<",
            "operator>>" => ">>",
            _ => string.Empty
        };
        return op.Length != 0;
    }

    private static bool TryMapAssignmentOperator(string? displayName, out string op)
    {
        op = displayName switch
        {
            "operator=" => "=",
            "operator+=" => "+=",
            "operator-=" => "-=",
            "operator*=" => "*=",
            "operator/=" => "/=",
            "operator%=" => "%=",
            "operator&=" => "&=",
            "operator|=" => "|=",
            "operator^=" => "^=",
            "operator<<=" => "<<=",
            "operator>>=" => ">>=",
            _ => string.Empty
        };
        return op.Length != 0;
    }

    protected virtual string LowerMemberCall(string receiver, string memberName, IReadOnlyList<string> arguments)
    {
        return $"{receiver}.{memberName}({string.Join(", ", arguments)})";
    }

    private string LowerForInitializer(CppslIrNode node)
    {
        if (node.Kind == "DeclarationStatement")
        {
            var declarations = node.Children
                .Where(static child => child.Kind == "LocalVariable")
                .Select(child =>
                {
                    var initializerNode = child.Children.LastOrDefault();
                    var hasExplicitInitializer = initializerNode is not null &&
                        !(initializerNode.Kind == "ConstructorCallExpression" && initializerNode.Children.Count == 0);
                    var initializer = !hasExplicitInitializer
                        ? string.Empty
                        : $" = {LowerExpression(initializerNode!)}";
                    return $"{MapValueType(child.Type ?? string.Empty)} {child.Spelling}{initializer}";
                })
                .ToArray();
            return string.Join(", ", declarations);
        }

        return LowerExpression(node);
    }

    protected virtual string LowerFunctionalCast(CppslIrNode node)
    {
        var type = MapValueType(node.Type ?? node.TypeInfo?.Spelling ?? node.Spelling);
        var argumentList = node.Children.Count == 1 && node.Children[0].Kind == "InitializerListExpression"
            ? string.Join(", ", node.Children[0].Children.Select(LowerExpression))
            : string.Join(", ", node.Children.Select(LowerExpression));
        return $"{type}({argumentList})";
    }

    protected virtual string LowerInitializerList(CppslIrNode node)
    {
        var argumentList = string.Join(", ", node.Children.Select(LowerExpression));
        var type = node.Type ?? node.TypeInfo?.Spelling;
        return string.IsNullOrWhiteSpace(type)
            ? argumentList
            : $"{MapValueType(type)}({argumentList})";
    }

    protected virtual string LowerMul(string left, string right)
    {
        return $"({left} * {right})";
    }

    protected virtual string FormatFloatingLiteral(string spelling)
    {
        return spelling;
    }

    protected void WriteDefaultReturn(StringBuilder builder, string returnType, CppslSemanticModel model, int indent)
    {
        if (returnType == "void")
        {
            return;
        }

        var prefix = new string(' ', indent * 4);
        builder.Append(prefix);
        builder.Append("return ");
        builder.Append(DefaultValue(returnType, model));
        builder.AppendLine(";");
    }

    protected string DefaultValue(string type, CppslSemanticModel model)
    {
        if (model.Structs.FirstOrDefault(structure => structure.Name == type) is { } structure)
        {
            return DefaultStructValue(structure, model);
        }

        var mappedType = MapValueType(type);
        return mappedType switch
        {
            "bool" => "false",
            "int" => "0",
            "uint" => "0u",
            "float" => "0.0",
            _ => DefaultAggregateValue(mappedType)
        };
    }

    protected abstract string MapValueType(string type);

    protected abstract string DefaultStructValue(CppslStruct structure, CppslSemanticModel model);

    protected abstract string DefaultAggregateValue(string mappedType);

    protected static bool IsCalleeReference(CppslIrNode? node, string calleeName)
    {
        if (node is null)
        {
            return false;
        }

        if (node.Kind == "DeclRefExpression" && node.DisplayName == calleeName)
        {
            return true;
        }

        return node.Children.Count == 1 && IsCalleeReference(node.Children[0], calleeName);
    }

    private bool TryGetMemberCall(
        CppslIrNode node,
        out string receiver,
        out string memberName,
        out IReadOnlyList<string> arguments)
    {
        receiver = string.Empty;
        memberName = string.Empty;
        arguments = Array.Empty<string>();

        if (node.Children.FirstOrDefault() is not { Kind: "MemberExpression" } member ||
            member.DisplayName is null ||
            member.Children.Count != 1)
        {
            return false;
        }

        receiver = LowerExpression(member.Children[0]);
        memberName = member.DisplayName;
        arguments = node.Children.Skip(1).Select(LowerExpression).ToArray();
        return true;
    }

    private static bool IsExpressionNode(CppslIrNode node)
    {
        return node.Kind.EndsWith("Expression", StringComparison.Ordinal) ||
            node.Kind.EndsWith("Literal", StringComparison.Ordinal) ||
            node.Kind == "DeclRefExpression" ||
            node.Kind == "MemberExpression" ||
            node.Kind == "OperatorCallExpression" ||
            node.Kind == "CallExpression";
    }
}
