using System.Text;
using CPPSL.Core.Artifacts;
using CPPSL.Core.Compiler;
using CPPSL.Core.Semantics;

namespace CPPSL.Core.Output;

public sealed class CppslShaderSourceEmitter
{
    public string Emit(CppslOutputTarget target, CppslCompileOptions options, CppslSemanticModel model)
    {
        return target switch
        {
            CppslOutputTarget.Hlsl => EmitHlsl(options, model),
            CppslOutputTarget.Glsl => EmitGlsl(options, model),
            CppslOutputTarget.Msl => EmitMsl(options, model),
            _ => throw new ArgumentOutOfRangeException(nameof(target), target, null)
        };
    }

    private static string EmitHlsl(CppslCompileOptions options, CppslSemanticModel model)
    {
        var builder = new StringBuilder();
        WriteHeader(builder, "HLSL", options);
        WriteStructs(builder, model, TargetSyntax.Hlsl);
        WriteHlslResources(builder, model);
        WriteEntryPoint(builder, options, model, TargetSyntax.Hlsl);
        return builder.ToString();
    }

    private static string EmitGlsl(CppslCompileOptions options, CppslSemanticModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("#version 450");
        WriteHeader(builder, "GLSL", options);
        WriteStructs(builder, model, TargetSyntax.Glsl);
        WriteGlslResources(builder, model);
        WriteEntryPoint(builder, options, model, TargetSyntax.Glsl);
        return builder.ToString();
    }

    private static string EmitMsl(CppslCompileOptions options, CppslSemanticModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("#include <metal_stdlib>");
        builder.AppendLine("using namespace metal;");
        builder.AppendLine();
        WriteHeader(builder, "MSL", options);
        WriteStructs(builder, model, TargetSyntax.Msl);
        WriteEntryPoint(builder, options, model, TargetSyntax.Msl);
        return builder.ToString();
    }

    private static void WriteHeader(StringBuilder builder, string targetName, CppslCompileOptions options)
    {
        builder.AppendLine("// Generated by cppslc phase 0.");
        builder.AppendLine($"// Target: {targetName}");
        builder.AppendLine($"// Entry: {options.EntryPoint}");
        builder.AppendLine($"// Stage: {options.Stage}");
        builder.AppendLine("// Function body lowering is pending; entry bodies return default values.");
        builder.AppendLine();
    }

    private static void WriteStructs(StringBuilder builder, CppslSemanticModel model, TargetSyntax syntax)
    {
        foreach (var structure in model.Structs)
        {
            builder.AppendLine($"struct {structure.Name}");
            builder.AppendLine("{");
            foreach (var field in structure.Fields)
            {
                var type = MapValueType(field.Type, syntax);
                var semantic = FieldSemantic(field, syntax);
                builder.Append("    ");
                builder.Append(type);
                builder.Append(' ');
                builder.Append(field.Name);
                builder.Append(semantic);
                builder.AppendLine(";");
            }
            builder.AppendLine("};");
            builder.AppendLine();
        }
    }

    private static void WriteHlslResources(StringBuilder builder, CppslSemanticModel model)
    {
        foreach (var global in model.Globals.Where(static global => global.ResourceKind is not null))
        {
            var declaration = global.ResourceKind switch
            {
                "constant_buffer" => $"ConstantBuffer<{UnwrapTemplateArgument(global.Type)}> {global.Name}",
                "structured_buffer" => $"StructuredBuffer<{UnwrapTemplateArgument(global.Type)}> {global.Name}",
                "rw_structured_buffer" => $"RWStructuredBuffer<{UnwrapTemplateArgument(global.Type)}> {global.Name}",
                "texture" => $"{global.Type} {global.Name}",
                "rw_texture" => $"{global.Type} {global.Name}",
                "sampler" => $"SamplerState {global.Name}",
                _ => $"{global.Type} {global.Name}"
            };

            builder.AppendLine($"{declaration} : register({HlslRegisterPrefix(global.ResourceKind)}{global.Binding}, space{global.DescriptorSet});");
        }

        if (model.Globals.Any(static global => global.ResourceKind is not null))
        {
            builder.AppendLine();
        }
    }

    private static void WriteGlslResources(StringBuilder builder, CppslSemanticModel model)
    {
        foreach (var global in model.Globals.Where(static global => global.ResourceKind is not null))
        {
            var layout = $"layout(set = {global.DescriptorSet}, binding = {global.Binding})";
            switch (global.ResourceKind)
            {
                case "constant_buffer":
                    builder.AppendLine($"{layout} uniform {global.Name}_Block");
                    builder.AppendLine("{");
                    builder.AppendLine($"    {MapValueType(UnwrapTemplateArgument(global.Type), TargetSyntax.Glsl)} {global.Name};");
                    builder.AppendLine("};");
                    break;
                case "texture":
                    builder.AppendLine($"{layout} uniform texture2D {global.Name};");
                    break;
                case "rw_texture":
                    builder.AppendLine($"{layout} uniform image2D {global.Name};");
                    break;
                case "sampler":
                    builder.AppendLine($"{layout} uniform sampler {global.Name};");
                    break;
                default:
                    builder.AppendLine($"{layout} buffer {global.Name}_Block");
                    builder.AppendLine("{");
                    builder.AppendLine($"    {MapValueType(UnwrapTemplateArgument(global.Type), TargetSyntax.Glsl)} {global.Name}[];");
                    builder.AppendLine("};");
                    break;
            }
        }

        if (model.Globals.Any(static global => global.ResourceKind is not null))
        {
            builder.AppendLine();
        }
    }

    private static void WriteEntryPoint(
        StringBuilder builder,
        CppslCompileOptions options,
        CppslSemanticModel model,
        TargetSyntax syntax)
    {
        var entryPoint = model.Functions.FirstOrDefault(function => function.Name == options.EntryPoint);
        if (entryPoint is null)
        {
            return;
        }

        var returnType = MapValueType(entryPoint.ReturnType ?? "void", syntax);
        builder.Append(StagePrefix(options, syntax));
        builder.Append(returnType);
        builder.Append(' ');
        builder.Append(entryPoint.Name);
        builder.Append('(');
        builder.Append(string.Join(", ", BuildEntryParameters(entryPoint, model, syntax)));
        builder.AppendLine(")");
        builder.AppendLine("{");
        builder.AppendLine("    // TODO: lower CPPSL IR body.");
        WriteDefaultReturn(builder, entryPoint.ReturnType ?? "void", model, syntax);
        builder.AppendLine("}");
    }

    private static IEnumerable<string> BuildEntryParameters(
        CppslFunction entryPoint,
        CppslSemanticModel model,
        TargetSyntax syntax)
    {
        foreach (var parameter in entryPoint.Parameters)
        {
            var type = MapValueType(parameter.Type, syntax);
            var stageIn = syntax == TargetSyntax.Msl ? " [[stage_in]]" : string.Empty;
            yield return $"{type} {parameter.Name}{stageIn}";
        }

        if (syntax != TargetSyntax.Msl)
        {
            yield break;
        }

        foreach (var global in model.Globals.Where(static global => global.ResourceKind is not null))
        {
            yield return BuildMslResourceParameter(global);
        }
    }

    private static string BuildMslResourceParameter(CppslGlobal global)
    {
        return global.ResourceKind switch
        {
            "constant_buffer" => $"constant {MapValueType(UnwrapTemplateArgument(global.Type), TargetSyntax.Msl)}& {global.Name} [[buffer({global.Binding})]]",
            "structured_buffer" => $"device const {MapValueType(UnwrapTemplateArgument(global.Type), TargetSyntax.Msl)}* {global.Name} [[buffer({global.Binding})]]",
            "rw_structured_buffer" => $"device {MapValueType(UnwrapTemplateArgument(global.Type), TargetSyntax.Msl)}* {global.Name} [[buffer({global.Binding})]]",
            "texture" => $"texture2d<float> {global.Name} [[texture({global.Binding})]]",
            "rw_texture" => $"texture2d<float, access::write> {global.Name} [[texture({global.Binding})]]",
            "sampler" => $"sampler {global.Name} [[sampler({global.Binding})]]",
            _ => $"{global.Type} {global.Name}"
        };
    }

    private static void WriteDefaultReturn(
        StringBuilder builder,
        string returnType,
        CppslSemanticModel model,
        TargetSyntax syntax)
    {
        if (returnType == "void")
        {
            return;
        }

        builder.Append("    return ");
        builder.Append(DefaultValue(returnType, model, syntax));
        builder.AppendLine(";");
    }

    private static string DefaultValue(string type, CppslSemanticModel model, TargetSyntax syntax)
    {
        if (model.Structs.FirstOrDefault(structure => structure.Name == type) is { } structure)
        {
            return syntax switch
            {
                TargetSyntax.Hlsl => $"({structure.Name})0",
                TargetSyntax.Msl => $"{structure.Name}{{}}",
                _ => $"{structure.Name}({string.Join(", ", structure.Fields.Select(field => DefaultValue(field.Type, model, syntax)))})"
            };
        }

        var mappedType = MapValueType(type, syntax);
        return mappedType switch
        {
            "bool" => "false",
            "int" => "0",
            "uint" => "0u",
            "float" => "0.0",
            _ when syntax == TargetSyntax.Hlsl => $"({mappedType})0",
            _ when syntax == TargetSyntax.Msl => $"{mappedType}(0)",
            _ => $"{mappedType}(0.0)"
        };
    }

    private static string FieldSemantic(CppslField field, TargetSyntax syntax)
    {
        if (syntax == TargetSyntax.Glsl)
        {
            return string.Empty;
        }

        if (field.IsPosition)
        {
            return syntax == TargetSyntax.Hlsl ? " : SV_Position" : " [[position]]";
        }

        if (field.Location is { } location)
        {
            return syntax == TargetSyntax.Hlsl ? $" : TEXCOORD{location}" : $" [[user(locn{location})]]";
        }

        return string.Empty;
    }

    private static string StagePrefix(CppslCompileOptions options, TargetSyntax syntax)
    {
        if (syntax != TargetSyntax.Msl)
        {
            return string.Empty;
        }

        return options.Stage switch
        {
            IR.ShaderStage.Vertex => "vertex ",
            IR.ShaderStage.Fragment or IR.ShaderStage.Pixel => "fragment ",
            IR.ShaderStage.Compute => "kernel ",
            _ => string.Empty
        };
    }

    private static string MapValueType(string type, TargetSyntax syntax)
    {
        return syntax switch
        {
            TargetSyntax.Glsl => type switch
            {
                "float2" => "vec2",
                "float3" => "vec3",
                "float4" => "vec4",
                "float4x4" => "mat4",
                "uint" => "uint",
                "bool_t" => "bool",
                _ => type
            },
            _ => type switch
            {
                "bool_t" => "bool",
                _ => type
            }
        };
    }

    private static string HlslRegisterPrefix(string? resourceKind)
    {
        return resourceKind switch
        {
            "constant_buffer" => "b",
            "rw_structured_buffer" or "rw_texture" => "u",
            "sampler" => "s",
            _ => "t"
        };
    }

    private static string UnwrapTemplateArgument(string type)
    {
        var open = type.IndexOf('<');
        var close = type.LastIndexOf('>');
        if (open < 0 || close <= open)
        {
            return type;
        }

        return type.Substring(open + 1, close - open - 1).Trim();
    }

    private enum TargetSyntax
    {
        Hlsl,
        Glsl,
        Msl
    }
}
