#include <clang/AST/AST.h>
#include <clang/AST/DeclCXX.h>
#include <clang/Basic/Diagnostic.h>
#include <clang/Frontend/ASTUnit.h>
#include <clang/Tooling/Tooling.h>
#include <llvm/Support/Casting.h>

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <memory>
#include <sstream>
#include <set>
#include <string>
#include <string_view>
#include <vector>

namespace
{
struct Options
{
    std::vector<std::string> headers;
    std::vector<std::string> include_roots;
    std::vector<std::string> defines;
    std::vector<std::string> undefines;
    std::string output_dir;
    std::string stamp;
    std::string depfile;
    std::string mode;
    std::string platform;
    std::string arch;
};

Options ParseOptions(int argc, char** argv)
{
    Options options;
    for (int i = 1; i < argc; ++i)
    {
        std::string_view arg(argv[i]);
        auto next = [&]() -> std::string {
            if (i + 1 >= argc)
            {
                return {};
            }
            return argv[++i];
        };

        if (arg == "--header")
        {
            options.headers.push_back(next());
        }
        else if (arg == "--include")
        {
            options.include_roots.push_back(next());
        }
        else if (arg == "--define")
        {
            options.defines.push_back(next());
        }
        else if (arg == "--undefine")
        {
            options.undefines.push_back(next());
        }
        else if (arg == "--output-dir")
        {
            options.output_dir = next();
        }
        else if (arg == "--stamp")
        {
            options.stamp = next();
        }
        else if (arg == "--depfile")
        {
            options.depfile = next();
        }
        else if (arg == "--mode")
        {
            options.mode = next();
        }
        else if (arg == "--platform")
        {
            options.platform = next();
        }
        else if (arg == "--arch")
        {
            options.arch = next();
        }
    }
    return options;
}

bool ReadTextFile(const std::filesystem::path& path, std::string& text)
{
    std::ifstream stream(path);
    if (!stream)
    {
        std::cerr << "error: cannot read file: " << path.string() << "\n";
        return false;
    }
    std::stringstream buffer;
    buffer << stream.rdbuf();
    text = buffer.str();
    return true;
}

std::string TrimLeft(std::string_view value)
{
    size_t pos = 0;
    while (pos < value.size() && (value[pos] == ' ' || value[pos] == '\t'))
    {
        ++pos;
    }
    return std::string(value.substr(pos));
}

bool EndsWith(std::string_view value, std::string_view suffix)
{
    return value.size() >= suffix.size() && value.substr(value.size() - suffix.size()) == suffix;
}

std::string GeneratedHeaderName(const std::filesystem::path& header)
{
    return header.stem().string() + ".generated.hpp";
}

std::filesystem::path GeneratedHeaderPath(const Options& options, const std::filesystem::path& header)
{
    return std::filesystem::path(options.output_dir) / GeneratedHeaderName(header);
}

bool WriteGeneratedHeader(const std::filesystem::path& path)
{
    std::filesystem::create_directories(path.parent_path());
    std::ofstream stream(path, std::ios::trunc);
    if (!stream)
    {
        std::cerr << "error: cannot write generated header: " << path.string() << "\n";
        return false;
    }
    stream << "// Autogenerated by LunaMetaTool, do not modify.\n";
    stream << "#pragma once\n";
    return true;
}

bool PrecreateGeneratedHeaders(const Options& options)
{
    std::set<std::string> names;
    for (const auto& header : options.headers)
    {
        auto name = GeneratedHeaderName(header);
        if (!names.insert(name).second)
        {
            std::cerr << "error: multiple meta headers generate the same file: " << name << "\n";
            return false;
        }
        if (!WriteGeneratedHeader(GeneratedHeaderPath(options, header)))
        {
            return false;
        }
    }
    return true;
}

std::string ParseIncludeTarget(const std::string& line)
{
    auto trimmed = TrimLeft(line);
    if (!trimmed.starts_with("#include"))
    {
        return {};
    }
    auto first_quote = trimmed.find('"');
    if (first_quote != std::string::npos)
    {
        auto second_quote = trimmed.find('"', first_quote + 1);
        if (second_quote != std::string::npos)
        {
            return trimmed.substr(first_quote + 1, second_quote - first_quote - 1);
        }
    }
    auto first_angle = trimmed.find('<');
    if (first_angle != std::string::npos)
    {
        auto second_angle = trimmed.find('>', first_angle + 1);
        if (second_angle != std::string::npos)
        {
            return trimmed.substr(first_angle + 1, second_angle - first_angle - 1);
        }
    }
    return {};
}

bool ValidateGeneratedIncludeOrder(const std::filesystem::path& header, const std::string& text, std::string& error)
{
    auto expected = GeneratedHeaderName(header);
    bool saw_generated_include = false;
    bool saw_expected = false;
    std::istringstream lines(text);
    std::string line;
    unsigned line_number = 0;
    while (std::getline(lines, line))
    {
        ++line_number;
        auto include = ParseIncludeTarget(line);
        if (include.empty())
        {
            continue;
        }
        const bool is_generated = EndsWith(include, ".generated.hpp");
        if (is_generated)
        {
            saw_generated_include = true;
            if (std::filesystem::path(include).filename() == expected)
            {
                saw_expected = true;
            }
            continue;
        }
        if (saw_generated_include)
        {
            error = header.string() + ":" + std::to_string(line_number) +
                ": non-generated include appears after a generated include";
            return false;
        }
    }
    if (!saw_expected)
    {
        error = header.string() + ": missing #include \"" + expected + "\"";
        return false;
    }
    return true;
}

bool IsInMainFile(const clang::SourceManager& sm, clang::SourceLocation location)
{
    if (location.isInvalid())
    {
        return false;
    }
    return sm.isWrittenInMainFile(sm.getSpellingLoc(location));
}

std::string SliceAroundDecl(
    const std::string& text,
    const clang::SourceManager& sm,
    const clang::Decl* decl)
{
    auto begin = sm.getSpellingLoc(decl->getBeginLoc());
    auto end = sm.getSpellingLoc(decl->getEndLoc());
    if (begin.isInvalid() || end.isInvalid())
    {
        return {};
    }
    const auto begin_offset = sm.getFileOffset(begin);
    const auto end_offset = sm.getFileOffset(end);
    const auto slice_begin = begin_offset > 256 ? begin_offset - 256 : 0;
    const auto slice_end = std::min<size_t>(text.size(), static_cast<size_t>(end_offset) + 512);
    if (slice_begin >= slice_end || slice_begin >= text.size())
    {
        return {};
    }
    return text.substr(slice_begin, slice_end - slice_begin);
}

void VisitDecls(
    const clang::DeclContext* context,
    const clang::ASTContext& ast_context,
    const std::string& source_text,
    unsigned& reflected_decl_count)
{
    const auto& sm = ast_context.getSourceManager();
    for (const auto* decl : context->decls())
    {
        if (const auto* record = llvm::dyn_cast<clang::CXXRecordDecl>(decl))
        {
            if (record->isCompleteDefinition() && IsInMainFile(sm, record->getLocation()))
            {
                auto slice = SliceAroundDecl(source_text, sm, record);
                if (slice.find("luna::struct") != std::string::npos)
                {
                    ++reflected_decl_count;
                }
            }
        }
        else if (const auto* enum_decl = llvm::dyn_cast<clang::EnumDecl>(decl))
        {
            if (enum_decl->isCompleteDefinition() && IsInMainFile(sm, enum_decl->getLocation()))
            {
                auto slice = SliceAroundDecl(source_text, sm, enum_decl);
                if (slice.find("luna::enum") != std::string::npos)
                {
                    ++reflected_decl_count;
                }
            }
        }

        if (const auto* child_context = llvm::dyn_cast<clang::DeclContext>(decl))
        {
            VisitDecls(child_context, ast_context, source_text, reflected_decl_count);
        }
    }
}

std::vector<std::string> BuildClangArgs(const Options& options, const std::filesystem::path& header)
{
    std::vector<std::string> args = {
        "-x",
        "c++",
        "-std=c++20",
        "-fsyntax-only",
        "-Wno-unknown-attributes",
        "-Wno-ignored-attributes"
    };
    for (const auto& include : options.include_roots)
    {
        args.push_back("-I" + include);
    }
    args.push_back("-I" + header.parent_path().string());
    for (const auto& define : options.defines)
    {
        args.push_back("-D" + define);
    }
    for (const auto& undefine : options.undefines)
    {
        args.push_back("-U" + undefine);
    }
    return args;
}

bool ParseHeader(const Options& options, const std::filesystem::path& header, unsigned& reflected_decl_count)
{
    std::string source_text;
    if (!ReadTextFile(header, source_text))
    {
        return false;
    }
    std::string include_error;
    if (!ValidateGeneratedIncludeOrder(header, source_text, include_error))
    {
        std::cerr << "error: " << include_error << "\n";
        return false;
    }

    auto ast_unit = clang::tooling::buildASTFromCodeWithArgs(
        source_text,
        BuildClangArgs(options, header),
        header.string(),
        "LunaMetaTool",
        std::make_shared<clang::PCHContainerOperations>(),
        clang::tooling::getClangStripDependencyFileAdjuster(),
        clang::tooling::FileContentMappings(),
        nullptr);

    if (!ast_unit)
    {
        std::cerr << "error: failed to parse meta header: " << header.string() << "\n";
        return false;
    }

    VisitDecls(ast_unit->getASTContext().getTranslationUnitDecl(), ast_unit->getASTContext(), source_text, reflected_decl_count);
    return WriteGeneratedHeader(GeneratedHeaderPath(options, header));
}

std::string EscapeDepfilePath(std::string value)
{
    std::replace(value.begin(), value.end(), '\\', '/');
    std::string result;
    result.reserve(value.size());
    for (char ch : value)
    {
        if (ch == ' ')
        {
            result.push_back('\\');
        }
        result.push_back(ch);
    }
    return result;
}

bool WriteDepfile(const Options& options)
{
    std::ofstream stream(options.depfile, std::ios::trunc);
    if (!stream)
    {
        std::cerr << "error: cannot write depfile: " << options.depfile << "\n";
        return false;
    }
    stream << EscapeDepfilePath(options.stamp) << ":";
    for (const auto& header : options.headers)
    {
        stream << " " << EscapeDepfilePath(header);
    }
    stream << "\n";
    return true;
}

bool WriteStamp(const Options& options, unsigned reflected_decl_count)
{
    std::filesystem::create_directories(std::filesystem::path(options.stamp).parent_path());
    std::ofstream stream(options.stamp, std::ios::trunc);
    if (!stream)
    {
        std::cerr << "error: cannot write stamp: " << options.stamp << "\n";
        return false;
    }
    stream << "reflected_declarations=" << reflected_decl_count << "\n";
    return true;
}
}

int main(int argc, char** argv)
{
    auto options = ParseOptions(argc, argv);
    if (options.headers.empty())
    {
        std::cerr << "error: missing --header\n";
        return 2;
    }
    if (options.output_dir.empty() || options.stamp.empty() || options.depfile.empty())
    {
        std::cerr << "error: missing --output-dir, --stamp, or --depfile\n";
        return 2;
    }

    if (!PrecreateGeneratedHeaders(options))
    {
        return 1;
    }

    unsigned reflected_decl_count = 0;
    bool succeeded = true;
    for (const auto& header : options.headers)
    {
        if (!ParseHeader(options, header, reflected_decl_count))
        {
            succeeded = false;
        }
    }
    if (!succeeded)
    {
        return 1;
    }

    if (!WriteDepfile(options) || !WriteStamp(options, reflected_decl_count))
    {
        return 1;
    }
    return 0;
}
