namespace CPPSL.Core.Frontend;

public enum CppslAstNodeKind
{
    Unknown,
    Namespace,
    Struct,
    Class,
    Enum,
    Field,
    Function,
    FunctionTemplate,
    ClassTemplate,
    GlobalVariable,
    LocalVariable,
    Parameter,
    Constructor,
    Method,
    CompoundStatement,
    DeclarationStatement,
    ReturnStatement,
    BinaryOperator,
    UnaryOperator,
    CallExpression,
    OperatorCallExpression,
    ConstructorCallExpression,
    FunctionalCastExpression,
    MemberExpression,
    DeclRefExpression,
    IntegerLiteral,
    FloatingLiteral,
    BooleanLiteral,
    StringLiteral,
    InitializerListExpression,
    ImplicitCastExpression,
    ParenExpression,
    ArraySubscriptExpression
}
