target("DemoApp")
    set_luna_sdk_program()
    add_files("**.cpp")
    add_deps("Runtime", "Window", "RHI", "ShaderCompiler", "Image")
    before_build(function(target)
        os.cp("$(scriptdir)/luna.png", target:targetdir() .. "/luna.png")
    end)
    after_install(function (target)
        os.cp(target:targetdir() .. "/luna.png", target:installdir() .. "/bin/luna.png")
    end)
target_end()