--[[
    configs: 
        output: Sets the output file.
            [default]: Outputs to $source$.cso on the current working directory.
        target_format: <dxil|spir_v|msl> Sets the target format.
            dxil: [Windows only] Outputs DirectX Intermediate Language for shader model 6.0 and newer.
            spir_v: Outputs SPIR-V for Vulkan API.
            msl: Outputs Metal library binary through the Apple Metal toolchain.
            [default]: `dxil` on Windows, `msl` on macOS.
        type: <vertex|pixel|compute> Sets the shader type.
            vertex: Compiles vertex shader.
            pixel: Compiles pixel/fragment shader.
            compute: Compiles compute shader.
            [default]: vertex
        entry_point: Sets the entry point function name.
            [default]: main
        optimize: <none|1|2> Sets the shader optimization level.
            none: Do not perform any optimization. This can be used if 
                you want to debug shader code using shader debugging tools.
            1: Specifies shader optimization level 1.
            2: Specifies shader optimization level 2.
            [default]: 2
        shader_model: <X_X> Sets the HLSL shader model version used when compiling HLSL source code.
            [default]: 6_0
        include_paths: Sets include search paths. This can be a table of multiple paths.
        definitions: Sets definitions (<DEF|DEF=VALUE>). This can be a table of multiple paths.
        debug: <true|false> Whether to keep debug information in the compiled shader.
            [default]: false
        skip_validation: <true|false> Whether to skip shader validation.
            [default]: false
        matrix_pack: <column|row> Sets the matrix pack mode.
            column: Use column major pack mode.
            row: Use row major pack mode.
            [default]: column
        metal_platform: <macos|ios> Sets the intended running platform for one metal shader.
            macos: The shader is intended to be running on macOS.
            ios: The shader is intended to be running on iOS/iPadOS.
            [default]: macos
        cpp_output: <true|false> Converts the shader output to C++ byte array, so that it can be embedded to the program directly.)";
            [default]: false
]]

local function read_binary(file)
    local f = io.open(file, "rb")
    if not f then
        os.raise("failed to open file for reading: " .. file)
    end
    local data = f:read("*a")
    f:close()
    return data
end

local function write_text(file, data)
    local dir = path.directory(file)
    if not os.isdir(dir) then
        os.mkdir(dir)
    end
    local f = io.open(file, "wb")
    if not f then
        os.raise("failed to open file for writing: " .. file)
    end
    f:write(data)
    f:close()
end

local function cpp_byte_array(data)
    local bytes = {}
    for i = 1, #data do
        table.insert(bytes, tostring(string.byte(data, i)))
    end
    return table.concat(bytes, ",")
end

local function metal_sdk(configs)
    if configs and configs.metal_platform == "ios" then
        return "iphoneos"
    end
    return "macosx"
end

local function trim_tool_path(value)
    return (value or ""):gsub("^%s+", ""):gsub("%s+$", "")
end

local function metal_tool_paths(sdk)
    local metal_path = nil
    local ok = try {
        function ()
            metal_path = trim_tool_path(os.iorunv("xcrun", {"-sdk", sdk, "-find", "metal"}))
            return true
        end
    }
    if not ok or metal_path == "" then
        os.raise("Metal shader binary generation requires Apple's Metal command-line tool: xcrun metal. Install Xcode, select it with xcode-select, then run xcodebuild -runFirstLaunch.")
    end
    local metallib_path = nil
    ok = try {
        function ()
            metallib_path = trim_tool_path(os.iorunv("xcrun", {"-sdk", sdk, "-find", "metallib"}))
            return true
        end
    }
    if not ok or metallib_path == "" then
        local sibling = path.join(path.directory(metal_path), "metallib")
        if os.isfile(sibling) then
            metallib_path = sibling
        else
            os.raise("Metal shader binary generation requires Apple's Metal library linker: xcrun metallib. Install the full Xcode Metal toolchain, select it with xcode-select, then run xcodebuild -runFirstLaunch.")
        end
    end
    return metal_path, metallib_path
end

local function read_hlsl_numthreads(shader_file)
    local source = read_binary(shader_file)
    local x, y, z = source:match("%[numthreads%s*%(%s*(%d+)%s*,%s*(%d+)%s*,%s*(%d+)%s*%)%]")
    return tonumber(x) or 0, tonumber(y) or 0, tonumber(z) or 0
end

local function write_shader_header(source_name, source_file, target_format, entry_point, output_file, metal_numthreads_x, metal_numthreads_y, metal_numthreads_z)
    local data = read_binary(source_file)
    local header = [[// Autogenerated by LunaShader, do not modify.
#pragma once
#include <Luna/ShaderCompiler/ShaderCompiler.hpp>

namespace Luna
{
    constexpr u8 SHADER_DATA_]] .. source_name .. "[] = {" .. cpp_byte_array(data) .. [[};
    constexpr usize SHADER_DATA_SIZE_]] .. source_name .. " = sizeof(SHADER_DATA_" .. source_name .. [[);
    constexpr ShaderCompiler::TargetFormat SHADER_DATA_FORMAT_]] .. source_name .. " = ShaderCompiler::TargetFormat::" .. target_format .. [[;
    constexpr c8 SHADER_ENTRY_POINT_]] .. source_name .. "[] = \"" .. entry_point .. [[";
    constexpr u32 SHADER_METAL_NUMTHREADS_X_]] .. source_name .. " = " .. tostring(metal_numthreads_x or 0) .. [[;
    constexpr u32 SHADER_METAL_NUMTHREADS_Y_]] .. source_name .. " = " .. tostring(metal_numthreads_y or 0) .. [[;
    constexpr u32 SHADER_METAL_NUMTHREADS_Z_]] .. source_name .. " = " .. tostring(metal_numthreads_z or 0) .. [[;
}]]
    write_text(output_file, header)
end

local function lunashader_bin_path()
    local bin_path = ""
    if os.host() == "windows" then
        bin_path = path.join(vformat("$(projectdir)"), "SDKs", "LunaShader", "windows", "x64", "LunaShader.exe")
    elseif os.host() == "macosx" then
        if os.arch() == "x86_64" then
            bin_path = path.join(vformat("$(projectdir)"), "SDKs", "LunaShader", "macosx", "x86_64", "LunaShader")
        elseif os.arch() == "arm64" then
            bin_path = path.join(vformat("$(projectdir)"), "SDKs", "LunaShader", "macosx", "arm64", "LunaShader")
        end
    end
    if bin_path == "" then
        os.raise("LunaShader is not supported on the current platform. (" .. os.host() .. "." .. os.arch() .. ")")
    end
    return bin_path
end

local function make_lunashader_args(shader_file, configs)
    local args = {}
    table.insert(args, shader_file)
    for k, v in pairs(configs) do
        if k == "output" then
            table.insert(args, "-o")
            table.insert(args, v)
        elseif k == "target_format" then
            table.insert(args, "-f")
            table.insert(args, v)
        elseif k == "type" then
            table.insert(args, "-t")
            table.insert(args, v)
        elseif k == "entry_point" then
            table.insert(args, "-e")
            table.insert(args, v)
        elseif k == "optimize" then
            table.insert(args, "--optimize")
            table.insert(args, v)
        elseif k == "shader_model" then
            table.insert(args, "-sm")
            table.insert(args, v)
        elseif k == "include_paths" then
            for _, p in ipairs(v) do
                table.insert(args, "-i")
                table.insert(args, p)
            end
        elseif k == "definitions" then
            for _, d in ipairs(v) do
                table.insert(args, "-d")
                table.insert(args, d)
            end
        elseif k == "debug" then
            if v == true then
                table.insert(args, "--debug")
            end
        elseif k == "skip_validation" then
            if v == true then
                table.insert(args, "--skip_validation")
            end
        elseif k == "matrix_pack" then
            table.insert(args, "--matrix_pack")
            table.insert(args, v)
        elseif k == "metal_platform" then
            table.insert(args, "--metal_platform")
            table.insert(args, v)
        elseif k == "cpp_output" then
            if v == true then
                table.insert(args, "--cpp_output")
            end
        end
    end
    return args
end

local function copy_configs(configs)
    local copied = {}
    for k, v in pairs(configs) do
        copied[k] = v
    end
    return copied
end

local function is_debug_enabled(configs)
    return configs and configs.debug == true
end

local function append_metal_debug_args(args, configs)
    if is_debug_enabled(configs) then
        table.insert(args, "-gline-tables-only")
        table.insert(args, "-frecord-sources")
    end
end

local function compile_metal_library(source_file, air_file, metallib_file, configs)
    local sdk = metal_sdk(configs)
    local metal_path, metallib_path = metal_tool_paths(sdk)
    local module_cache = path.join(vformat("$(projectdir)"), "build", ".metal-module-cache")
    if not os.isdir(module_cache) then
        os.mkdir(module_cache)
    end
    local args = {
        "-std=metal3.2",
        "-fmodules-cache-path=" .. module_cache,
        "-x",
        "metal",
        "-c",
        source_file,
        "-o",
        air_file
    }
    append_metal_debug_args(args, configs)
    os.runv(metal_path, args)
    os.runv(metallib_path, {
        air_file,
        "-o",
        metallib_file
    })
end

local function compile_metal_shader(shader_file, configs)
    local output_file = configs.output or (path.basename(shader_file) .. ".metallib")
    local source_name = path.basename(shader_file)
    local generated_dir = path.join(path.directory(output_file), ".metal", source_name)
    if not os.isdir(generated_dir) then
        os.mkdir(generated_dir)
    end
    local metal_source = path.join(generated_dir, source_name .. ".metal")
    local air_file = path.join(generated_dir, source_name .. ".air")
    local metallib_file = output_file
    if configs.cpp_output == true then
        metallib_file = path.join(generated_dir, source_name .. ".metallib")
    end

    local source_configs = copy_configs(configs)
    source_configs.output = metal_source
    source_configs.cpp_output = false
    os.runv(lunashader_bin_path(), make_lunashader_args(shader_file, source_configs))
    compile_metal_library(metal_source, air_file, metallib_file, configs)

    if configs.cpp_output == true then
        local nx, ny, nz = read_hlsl_numthreads(shader_file)
        write_shader_header(source_name, metallib_file, "metallib", configs.entry_point or "main", output_file, nx, ny, nz)
    end
end

function compile_shader(shader_file, configs)
    if configs.target_format == "msl" then
        compile_metal_shader(shader_file, configs)
        return
    end
    os.runv(lunashader_bin_path(), make_lunashader_args(shader_file, configs))
end

function shader_to_cpp(file, shader_type)
    local shader_path = path.join(vformat("$(scriptdir)"), file)
    local target_path = path.join(vformat("$(buildir)"), file)
    local configs = {
        output = target_path,
        target_format = "dxil",
        type = shader_type,
        optimize = "2",
        cpp_output = true
    }
    compile_shader(shader_path, configs)
end
