using System.Text;

namespace LunaBuild.Core.MakeSystem;

public sealed class BinaryEmbedHeaderActionExecutor : KnownActionExecutor
{
    public BinaryEmbedHeaderActionExecutor()
        : base("bin.embed_header")
    {
    }

    public override Task ExecuteAsync(MakeActionContext context, CancellationToken cancellationToken)
    {
        var payload = ActionPayload.Parse(context.ActionPayload);
        var source = context.Workspace.ResolveRepositoryPath(payload.Required("source"));
        var output = context.Workspace.ResolveRepositoryPath(payload.Required("output"));
        var dataSymbol = payload.Required("data_symbol");
        var sizeSymbol = payload.Required("size_symbol");

        cancellationToken.ThrowIfCancellationRequested();
        Directory.CreateDirectory(Path.GetDirectoryName(output)!);
        var bytes = File.ReadAllBytes(source);

        var builder = new StringBuilder();
        builder.AppendLine("// Autogenerated by LunaBuild, do not modify.");
        builder.AppendLine("#pragma once");
        builder.Append("static constexpr unsigned char ").Append(dataSymbol).Append("[] = {");
        for(var i = 0; i < bytes.Length; ++i)
        {
            if(i != 0)
            {
                builder.Append(',');
            }
            builder.Append(bytes[i]);
        }
        builder.AppendLine("};");
        builder.Append("static constexpr unsigned long long ").Append(sizeSymbol).Append(" = sizeof(").Append(dataSymbol).AppendLine(");");
        File.WriteAllText(output, builder.ToString());
        return Task.CompletedTask;
    }
}
