using System.Text;
using System.Text.Json;

namespace LunaBuild.Core;

public static class BuildRuleFileWriter
{
    public static void Write(BuildGraph graph, string outputPath)
    {
        var directory = Path.GetDirectoryName(Path.GetFullPath(outputPath));
        if(!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        ValidateGraph(graph);

        using var writer = new StreamWriter(outputPath, append: false, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        Write(graph, writer);
    }

    public static string ToText(BuildGraph graph)
    {
        ValidateGraph(graph);

        using var text = new StringWriter();
        Write(graph, text);
        return text.ToString();
    }

    private static void Write(BuildGraph graph, TextWriter writer)
    {
        writer.WriteLine($"luna_make {graph.Version}");
        writer.WriteLine("# Generated by LunaBuild. This is an expanded execution graph, not a project script.");
        writer.WriteLine($"option {Q("mode")} {Q(graph.Options.Mode.ToString())}");
        writer.WriteLine($"option {Q("platform")} {Q(graph.Options.Platform.ToString())}");
        writer.WriteLine($"option {Q("architecture")} {Q(graph.Options.Architecture)}");
        writer.WriteLine($"option {Q("rhi")} {Q(graph.Options.RhiApi.ToString())}");
        writer.WriteLine($"option {Q("shared")} {JsonSerializer.Serialize(graph.Options.Shared)}");
        foreach(var property in graph.Options.Properties.Values)
        {
            writer.WriteLine($"option {Q("property." + property.Name)} {Q(property.Value)}");
        }
        writer.WriteLine();

        foreach(var project in graph.Projects)
        {
            writer.WriteLine($"project {Q(project.Name)} {Q(project.RootDirectory)} {Q(project.BuildDirectory)} {JsonSerializer.Serialize(project.IsHost)}");
        }
        foreach(var configuration in graph.Configurations)
        {
            writer.WriteLine($"configuration {Q(configuration.Id)} {Q(configuration.ProjectName)} {Q(JsonSerializer.Serialize(configuration.Options))}");
        }
        writer.WriteLine();

        foreach(var target in graph.Targets)
        {
            writer.WriteLine($"target {Q(target)}");
        }
        writer.WriteLine();

        foreach(var node in graph.Nodes)
        {
            writer.WriteLine($"node {Q(node.Id)} {NodeKind(node.Kind)} {NullableQ(node.Path)}");
            if(!string.IsNullOrWhiteSpace(node.ProjectName) || !string.IsNullOrWhiteSpace(node.ConfigurationId))
            {
                writer.WriteLine($"node_config {Q(node.Id)} {Q(node.ProjectName)} {Q(node.ConfigurationId)}");
            }
        }
        writer.WriteLine();

        foreach(var node in graph.Nodes)
        {
            if(!string.IsNullOrWhiteSpace(node.Command))
            {
                writer.WriteLine($"action {Q(node.Id)} {Q(BuildActionKind.Extract(node.Command))} {Q(node.Command)}");
            }

            foreach(var dependency in node.Dependencies)
            {
                writer.WriteLine($"dep {Q(node.Id)} {Q(dependency)}");
            }

            foreach(var dependency in node.OrderOnlyDependencies)
            {
                writer.WriteLine($"order {Q(node.Id)} {Q(dependency)}");
            }

            foreach(var output in node.Outputs)
            {
                writer.WriteLine($"output {Q(node.Id)} {Q(output)}");
            }

            foreach(var depfile in node.Depfiles)
            {
                writer.WriteLine($"depfile {Q(node.Id)} {Q(depfile)}");
            }
        }
    }

    private static void ValidateGraph(BuildGraph graph)
    {
        if(graph.Version is not (1 or 2))
        {
            throw new InvalidOperationException($"Unsupported build graph version: {graph.Version}");
        }

        if(graph.Version == 2)
        {
            ValidateMetadata(graph);
        }

        var nodeIds = new HashSet<string>(StringComparer.Ordinal);
        var filePaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach(var node in graph.Nodes)
        {
            if(!nodeIds.Add(node.Id))
            {
                throw new InvalidOperationException($"Duplicate build node id: {node.Id}");
            }

            if(node.Kind == BuildGraphNodeKind.File)
            {
                if(string.IsNullOrWhiteSpace(node.Path))
                {
                    throw new InvalidOperationException($"File node has no path: {node.Id}");
                }
                if(!filePaths.Add(node.Path))
                {
                    throw new InvalidOperationException($"Duplicate file node path: {node.Path}");
                }
            }
        }

        foreach(var target in graph.Targets)
        {
            RequireNode(nodeIds, target, "target");
        }

        foreach(var node in graph.Nodes)
        {
            foreach(var dependency in node.Dependencies)
            {
                RequireNode(nodeIds, dependency, $"dependency of {node.Id}");
            }

            foreach(var dependency in node.OrderOnlyDependencies)
            {
                RequireNode(nodeIds, dependency, $"order-only dependency of {node.Id}");
            }

            foreach(var output in node.Outputs)
            {
                RequireNode(nodeIds, output, $"output of {node.Id}");
            }

            foreach(var depfile in node.Depfiles)
            {
                RequireNode(nodeIds, depfile, $"depfile of {node.Id}");
            }
        }
    }

    private static void ValidateMetadata(BuildGraph graph)
    {
        var projects = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach(var project in graph.Projects)
        {
            if(!projects.Add(project.Name))
            {
                throw new InvalidOperationException($"Duplicate build graph project: {project.Name}");
            }
        }

        var configurations = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach(var configuration in graph.Configurations)
        {
            if(!projects.Contains(configuration.ProjectName))
            {
                throw new InvalidOperationException(
                    $"Build graph configuration `{configuration.Id}` references unknown project `{configuration.ProjectName}`.");
            }
            if(!configurations.Add(ConfigurationKey(configuration.ProjectName, configuration.Id)))
            {
                throw new InvalidOperationException(
                    $"Duplicate build graph configuration: {configuration.ProjectName}/{configuration.Id}");
            }
        }

        foreach(var node in graph.Nodes)
        {
            if(string.IsNullOrWhiteSpace(node.ProjectName) && string.IsNullOrWhiteSpace(node.ConfigurationId))
            {
                continue;
            }
            if(string.IsNullOrWhiteSpace(node.ProjectName) || string.IsNullOrWhiteSpace(node.ConfigurationId) ||
                !configurations.Contains(ConfigurationKey(node.ProjectName, node.ConfigurationId)))
            {
                throw new InvalidOperationException(
                    $"Build graph node `{node.Id}` references unknown configuration `{node.ProjectName}/{node.ConfigurationId}`.");
            }
        }
    }

    private static string ConfigurationKey(string projectName, string configurationId)
    {
        return projectName + "\n" + configurationId;
    }

    private static void RequireNode(HashSet<string> nodeIds, string nodeId, string usage)
    {
        if(!nodeIds.Contains(nodeId))
        {
            throw new InvalidOperationException($"Undefined build node referenced as {usage}: {nodeId}");
        }
    }

    private static string NodeKind(BuildGraphNodeKind kind)
    {
        return kind switch
        {
            BuildGraphNodeKind.File => "file",
            BuildGraphNodeKind.Phony => "phony",
            BuildGraphNodeKind.Virtual => "virtual",
            _ => throw new ArgumentOutOfRangeException(nameof(kind), kind, null),
        };
    }

    private static string NullableQ(string? value)
    {
        return value is null ? "null" : Q(value);
    }

    private static string Q(string value)
    {
        return JsonSerializer.Serialize(value);
    }
}
