function luna_rhi_csharp_test_target(name, entrypoint)
    target(name)
        set_kind("binary")
        set_group("Tests")
        add_files("*.cs")
        add_files(entrypoint)
        add_deps("Luna.Runtime", "Luna.Window", "Luna.RHI", "Luna.RHIUtility", "Luna.ShaderCompiler", "Luna.Image")
        set_luna_sdk_csharp_options()
        after_build(function(target)
            os.cp(path.join("$(projectdir)", "Tests", "RHITests", "RHITest3_Texture", "uv_checker.png"), path.join(target:targetdir(), "uv_checker.png"))
        end)
        after_clean(function(target)
            os.rm(path.join(target:targetdir(), "uv_checker.png"))
        end)
    target_end()
end

luna_rhi_csharp_test_target("RHICSharpTest", "EntryPoints/All.cs")
luna_rhi_csharp_test_target("RHICSharpTest0_Empty", "EntryPoints/Empty.cs")
luna_rhi_csharp_test_target("RHICSharpTest1_Clear", "EntryPoints/Clear.cs")
luna_rhi_csharp_test_target("RHICSharpTest2_Triangle", "EntryPoints/Triangle.cs")
luna_rhi_csharp_test_target("RHICSharpTest3_Texture", "EntryPoints/Texture.cs")
luna_rhi_csharp_test_target("RHICSharpTest4_Box", "EntryPoints/Box.cs")
