luna_sdk_module_target("RHIUtility")
    add_rules("luna.shader")
    add_headerfiles("**.hpp")
    add_files("Source/**.cpp")
    add_deps("Runtime", "RHI")
    add_luna_shader("Source/Shaders/MipmapGeneration1DCS.hlsl", {type = "compute"})
    add_luna_shader("Source/Shaders/MipmapGeneration2DCS.hlsl", {type = "compute"})
    add_luna_shader("Source/Shaders/MipmapGeneration3DCS.hlsl", {type = "compute"})
target_end()