target("Luna.ShaderCompiler")
    set_kind("shared")
    add_files("*.cs")
    add_files("Internal/*.cs")
    add_deps("Luna.Runtime", "ShaderCompilerC")
    set_luna_sdk_csharp_options()
target_end()
