luna_sdk_module_target("ECS")
    add_headerfiles("*.hpp", {prefixdir = "Luna/ECS"})
    add_headerfiles("Source/**.hpp", {install = false})
    add_files("Source/**.cpp")
    add_deps("Runtime", "JobSystem")
target_end()