target("MultiPlatformSample")
    set_luna_sdk_program()
    add_files("Source/**.cpp")
    add_deps("Runtime", "Window", "RHI", "RHIUtility", "ShaderCompiler", "Image")
    before_build (function (target)
        os.cp("$(scriptdir)/Res/luna.png", target:targetdir() .. "/luna.png")
    end)
    after_install (function (target)
        os.cp(target:targetdir() .. "/luna.png", target:installdir() .. "/bin/luna.png")
    end)
target_end()