target("Luna.AHI")
    set_kind("shared")
    add_files("*.cs")
    add_files("Internal/*.cs")
    add_files("Internal/Generated/*.cs")
    add_deps("Luna.Runtime", "AHIC")
    set_luna_sdk_csharp_options()
target_end()
