luna_sdk_module_target("Frontend")
    add_headerfiles("*.hpp", {prefixdir = "Luna/Frontend"})
    add_headerfiles("Source/**.hpp", {install = false})
    add_files("Source/**.cpp")
    add_deps("Runtime")
target_end()
