/*!
* This file is a portion of LunaSDK.
* For conditions of distribution and use, see the disclaimer
* and license in LICENSE.txt
* 
* @file ShapeRenderer.hpp
* @author JXMaster
* @date 2023/9/27
*/
#pragma once
#include "ShapeDrawList.hpp"
#include <Luna/RHI/CommandBuffer.hpp>
#include <Luna/Runtime/Math/Matrix.hpp>
#include "ShapeRenderer.generated.hpp"

namespace Luna
{
    namespace VG
    {
        //! @addtogroup VG
        //! @{

        //! Describes the render-pass compatibility and fixed-function state used by one shape-renderer recording.
        struct ShapeRendererPassDesc
        {
            //! Color render target used to select the pipeline format and viewport dimensions.
            RHI::ITexture* render_target = nullptr;
            //! Depth-stencil attachment format of the caller-owned render pass.
            RHI::Format depth_stencil_format = RHI::Format::unknown;
            //! Whether depth testing is enabled.
            bool depth_test_enable = false;
            //! Whether passing shape fragments write depth.
            bool depth_write_enable = false;
            //! Depth comparison function used when depth testing is enabled.
            RHI::CompareFunction depth_compare_function = RHI::CompareFunction::less_equal;
            //! Triangle culling mode used by the shape pipeline.
            RHI::CullMode cull_mode = RHI::CullMode::none;

            //! Constructs an empty pass description.
            ShapeRendererPassDesc() = default;
            //! Constructs a color-only pass description.
            //! @param[in] render_target The color target used by the pass.
            explicit ShapeRendererPassDesc(RHI::ITexture* render_target) :
                render_target(render_target) {}
        };
        
        //! @interface
        //! Represents one renderer that processes draw calls generated by @ref IShapeDrawList.
        struct [[Luna::interface("{C0FBD0AE-B7F6-4A82-A59B-B1115ACCBD94}")]] IShapeRenderer : virtual Interface
        {
            //! Starts recording draw calls for a color-only pass.
            //! @param[in] render_target The texture to use for rendering draw calls.
            RV begin(RHI::ITexture* render_target)
            {
                return begin(ShapeRendererPassDesc(render_target));
            }

            //! Starts recording draw calls.
            //! @remark This call will clear all RHI resorurces used for previous draw calls, so call this
            //! function only after the previous render commands are finished by GPU.
            //! @param[in] desc The caller-owned render-pass formats and fixed-function state.
            virtual RV begin(const ShapeRendererPassDesc& desc) = 0;

            //! Adds draw calls to this renderer.
            //! @param[in] instance_buffer The instance buffer fetched from @ref IShapeDrawList::get_instance_buffer.
            //! @param[in] state_buffer The state buffer fetched from @ref IShapeDrawList::get_state_buffer.
            //! @param[in] draw_calls The shape draw calls fetched from @ref IShapeDrawList::get_draw_calls.
            //! @param[in] transform_matrix The projection transform matrix applied to vertices. If this is `nullptr`,
            //! an orthographic projection matching the render target dimensions is used.
            virtual void draw(
                RHI::IBuffer* instance_buffer,
                RHI::IBuffer* state_buffer,
                Span<const ShapeDrawCall> draw_calls,
                Float4x4U* transform_matrix = nullptr
            ) = 0;

            //! Finishes recording draw calls and refreshes RHI resources.
            virtual RV end() = 0;

            //! Prepares resources referenced by the recorded draw calls for rendering.
            //! @param[in] cmdbuf The command buffer used to record resource barriers.
            //! @remark This function must be called outside a render pass after @ref end and before @ref submit.
            //! The caller remains responsible for transitioning the render target itself.
            virtual void prepare(RHI::ICommandBuffer* cmdbuf) = 0;

            //! Generates RHI draw commands to the specified command buffer.
            //! @param[in] cmdbuf The command buffer used to record shape draw calls.
            //! @param[in] first_draw_call The first recorded draw call to submit.
            //! @param[in] num_draw_calls The maximum number of draw calls to submit. @ref U32_MAX submits all
            //! remaining draw calls.
            //! @remark The caller must begin a compatible render pass before calling this function and end the
            //! render pass afterwards. Call @ref prepare outside that render pass before the first submission.
            virtual void submit(RHI::ICommandBuffer* cmdbuf, u32 first_draw_call = 0, u32 num_draw_calls = U32_MAX) = 0;
        };

        //! Creates a new shape renderer that draws filled shape contours.
        //! @param[in] render_target The texture used as the render target of the renderer.
        //! @return Returns the created shape renderer.
        LUNA_VG_API Ref<IShapeRenderer> new_fill_shape_renderer();

        //! @}
    }
}
