target("RHITest4_Box")
    add_luna_sdk_options()
    add_rules("luna.shader")
    set_group("Tests/RHITest")
    set_kind("binary")
    add_files("*.cpp")
    add_luna_shader("TestBoxVS.hlsl", {type = "vertex"})
    add_luna_shader("TestBoxPS.hlsl", {type = "pixel"})
    add_deps("Runtime", "RHI", "RHITestBed", "ShaderCompiler", "Image")
    after_build(function(target)
        os.cp(path.join("$(scriptdir)", "luna.png"), path.join(target:targetdir(), "luna.png"))
    end)
    after_clean(function(target)
        os.rm(path.join(target:targetdir(), "luna.png"))
    end)
    after_install(function (target)
        os.cp(path.join(target:targetdir(), "luna.png"), path.join(target:installdir(), "bin", "luna.png"))
    end)
    after_uninstall(function (target)
        os.rm(path.join(target:installdir(), "bin", "luna.png"))
    end)
target_end()