target("RHITest4_Box")
    add_luna_sdk_options()
    set_group("Tests/RHITest")
    set_kind("binary")
    add_files("*.cpp")
    add_deps("Runtime", "RHI", "RHITestBed", "ShaderCompiler", "Image")
    before_build(function(target)
        os.cp("$(scriptdir)/luna.png", target:targetdir() .. "/luna.png")
    end)
    after_install(function (target)
        os.cp(target:targetdir() .. "/luna.png", target:installdir() .. "/bin/luna.png")
    end)
target_end()