target("RHITest1_FillBackBuffer")
    add_luna_sdk_options()
    set_group("Tests/RHITest")
    set_kind("binary")
    add_files("*.cpp")
    add_luna_modules("Runtime", "RHI", "RHITestBed")
target_end()