target("RHITest3_Texture")
    add_luna_sdk_options()
    add_rules("luna.shader")
    set_group("Tests/RHITest")
    set_kind("binary")
    add_files("*.cpp")
    add_files("TestTextureVS.hlsl", {type = "vertex"})
    add_files("TestTexturePS.hlsl", {type = "pixel"})
    add_deps("Runtime", "RHI", "RHITestBed", "ShaderCompiler", "Image")
    after_build(function(target)
        os.cp(path.join("$(scriptdir)", "uv_checker.png"), path.join(target:targetdir(), "uv_checker.png"))
    end)
    after_clean(function(target)
        os.rm(path.join(target:targetdir(), "uv_checker.png"))
    end)
    after_install(function (target)
        os.cp(path.join(target:targetdir(), "uv_checker.png"), path.join(target:installdir(), "bin", "uv_checker.png"))
    end)
    after_uninstall(function (target)
        os.rm(path.join(target:installdir(), "bin", "uv_checker.png"))
    end)
target_end()