-- Legacy/reference xmake script.
-- LunaBuild *.Target.cs rules are authoritative for main-path and CI builds.
-- Keep this file only as migration reference while old branches are being ported.

target("RHITest3_Texture")
    add_luna_sdk_options()
    add_rules("luna.shader")
    set_group("Tests/RHITest")
    set_kind("binary")
    add_files("*.cpp")
    add_luna_shader("TestTextureVS.cxx", {type = "vertex", entry_point = "vs_main"})
    add_luna_shader("TestTexturePS.cxx", {type = "pixel", entry_point = "ps_main"})
    add_deps("Runtime", "RHI", "RHIUtility", "RHITestBed", "Image")
    after_build(function(target)
        os.cp(path.join("$(scriptdir)", "uv_checker.png"), path.join(target:targetdir(), "uv_checker.png"))
    end)
    after_clean(function(target)
        os.rm(path.join(target:targetdir(), "uv_checker.png"))
    end)
    after_install(function (target)
        os.cp(path.join(target:targetdir(), "uv_checker.png"), path.join(target:installdir(), "bin", "uv_checker.png"))
    end)
    after_uninstall(function (target)
        os.rm(path.join(target:installdir(), "bin", "uv_checker.png"))
    end)
target_end()
