target("RHITest3_Texture")
    add_luna_sdk_options()
    set_group("Tests/RHITest")
    set_kind("binary")
    add_headerfiles("*.hpp")
    add_files("*.cpp")
    add_deps("Runtime", "RHI", "RHITestBed", "ShaderCompiler")
target_end()