target("Luna.ImGui")
    set_kind("shared")
    add_files("*.cs")
    add_files("Internal/*.cs")
    add_deps("Luna.Runtime", "Luna.Window", "Luna.RHI", "ImGuiC")
    set_luna_sdk_csharp_options()
target_end()
