name: macos-build

on: [push, pull_request]

jobs:
  build_macos:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]
        arch: [ x86_64, arm64 ]
        shared : [shared, static]
    name: ${{ matrix.arch }}-${{ matrix.shared }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Show .NET info
        run: dotnet --info

      - name: Restore SDK cache
        uses: actions/cache@v4
        with:
          path: |
            SDKs
            build/LunaSetup
          key: LunaSDK-SDKs-v6-d3d12ma-config-libs-macosx

      - name: Setup project
        run: |
          chmod +x ./setup.sh
          ./setup.sh

      - name: Build LunaBuild
        run: dotnet build Tools/LunaBuild/src/LunaBuild.Cli/LunaBuild.Cli.csproj --nologo

      - name: Build debug
        run: |
          if [ "${{ matrix.shared }}" = "shared" ]; then linkage="--shared"; else linkage="--static"; fi
          dotnet run --project Tools/LunaBuild/src/LunaBuild.Cli/LunaBuild.Cli.csproj -- build --all --mode Debug --platform MacOS --arch ${{ matrix.arch }} --rhi Metal "$linkage"

      - name: Install debug
        run: |
          if [ "${{ matrix.shared }}" = "shared" ]; then linkage="--shared"; else linkage="--static"; fi
          dotnet run --project Tools/LunaBuild/src/LunaBuild.Cli/LunaBuild.Cli.csproj -- install --all --mode Debug --platform MacOS --arch ${{ matrix.arch }} --rhi Metal "$linkage" --output ./install/${{ matrix.arch }}-debug

      - name: Build release
        run: |
          if [ "${{ matrix.shared }}" = "shared" ]; then linkage="--shared"; else linkage="--static"; fi
          dotnet run --project Tools/LunaBuild/src/LunaBuild.Cli/LunaBuild.Cli.csproj -- build --all --mode Release --platform MacOS --arch ${{ matrix.arch }} --rhi Metal "$linkage"

      - name: Install release
        run: |
          if [ "${{ matrix.shared }}" = "shared" ]; then linkage="--shared"; else linkage="--static"; fi
          dotnet run --project Tools/LunaBuild/src/LunaBuild.Cli/LunaBuild.Cli.csproj -- install --all --mode Release --platform MacOS --arch ${{ matrix.arch }} --rhi Metal "$linkage" --output ./install/${{ matrix.arch }}-release

      - name: Collect artifacts debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.shared }}-debug
          path: ./install/${{ matrix.arch }}-debug
          
      - name: Collect artifacts release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.shared }}-release
          path: ./install/${{ matrix.arch }}-release
