name: windows-build

on: [push, pull_request]

jobs:
  build_windows:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        arch: [ x64 ]
        toolchain: [ msvc ]
        rhi_api: [ D3D12, Vulkan ]
        shared: [ shared, static ]
    name: ${{ matrix.toolchain }}-${{ matrix.arch }}-${{ matrix.rhi_api }}-${{ matrix.shared }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Show .NET info
        run: dotnet --info

      - name: Restore SDK cache
        uses: actions/cache@v4
        with:
          path: |
            SDKs
            build/LunaSetup
          key: LunaSDK-SDKs-v6-d3d12ma-config-libs-windows

      - name: Setup project
        run: ./setup.bat

      - name: Build LunaBuild
        run: dotnet build LunaBuild.csproj --nologo

      - name: Build debug
        run: |
          $linkage = if ("${{ matrix.shared }}" -eq "shared") { "--shared" } else { "--static" }
          dotnet run --project LunaBuild.csproj -- build --all --mode Debug --platform Windows --arch ${{ matrix.arch }} --rhi ${{ matrix.rhi_api }} $linkage

      - name: Install debug
        run: |
          $linkage = if ("${{ matrix.shared }}" -eq "shared") { "--shared" } else { "--static" }
          dotnet run --project LunaBuild.csproj -- install --all --mode Debug --platform Windows --arch ${{ matrix.arch }} --rhi ${{ matrix.rhi_api }} $linkage --output ./install/${{ matrix.toolchain }}-${{ matrix.arch }}-${{ matrix.rhi_api }}-debug

      - name: Build release
        run: |
          $linkage = if ("${{ matrix.shared }}" -eq "shared") { "--shared" } else { "--static" }
          dotnet run --project LunaBuild.csproj -- build --all --mode Release --platform Windows --arch ${{ matrix.arch }} --rhi ${{ matrix.rhi_api }} $linkage

      - name: Install release
        run: |
          $linkage = if ("${{ matrix.shared }}" -eq "shared") { "--shared" } else { "--static" }
          dotnet run --project LunaBuild.csproj -- install --all --mode Release --platform Windows --arch ${{ matrix.arch }} --rhi ${{ matrix.rhi_api }} $linkage --output ./install/${{ matrix.toolchain }}-${{ matrix.arch }}-${{ matrix.rhi_api }}-release

      - name: Collect artifacts debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.toolchain }}-${{ matrix.arch }}-${{ matrix.rhi_api }}-${{ matrix.shared }}-debug
          path: ./install/${{ matrix.toolchain }}-${{ matrix.arch }}-${{ matrix.rhi_api }}-debug

      - name: Collect artifacts release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.toolchain }}-${{ matrix.arch }}-${{ matrix.rhi_api }}-${{ matrix.shared }}-release
          path: ./install/${{ matrix.toolchain }}-${{ matrix.arch }}-${{ matrix.rhi_api }}-release
