luna_sdk_module_target("ImGui")
    add_headerfiles("*.hpp", {prefixdir = "Luna/ImGui"})
    add_headerfiles("*.h", {prefixdir = "Luna/ImGui"})
    add_headerfiles("Source/**.h", {install = false})
    add_files("Source/**.cpp")
    add_includedirs(".")
    add_defines("LUNA_IMGUI_IMPL")
    add_deps("Window", "Runtime", "RHI", "HID", "Font", "ShaderCompiler")
target_end()
